version: '3'
services:
  fastapi:
    build: .
    ports:
      - 80:80
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "80"
      ]
